// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sallvat.Infrastructure.Persistence;

#nullable disable

namespace Sallvat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SallvatDbContext))]
    [Migration("20260910174859_AddOrderLifecycle")]
    partial class AddOrderLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_sequence")
                .StartsAt(1000L);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_application_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_application_role_normalized_name");

                    b.ToTable("application_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01990b9a-6c57-7ebf-9c06-2fb7680aa8dc"),
                            ConcurrencyStamp = "01990b9a-6c57-7ebf-9c06-2fb7680aa8dc",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("01990b9a-6c57-7ebf-9c06-33b5d3ee1511"),
                            ConcurrencyStamp = "01990b9a-6c57-7ebf-9c06-33b5d3ee1511",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_application_role_claim");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_application_role_claim_role_id");

                    b.ToTable("application_role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_application_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_application_user_claim_user_id");

                    b.ToTable("application_user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_application_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_application_user_login_user_id");

                    b.ToTable("application_user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_application_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_application_user_role_role_id");

                    b.ToTable("application_user_role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_application_user_token");

                    b.ToTable("application_user_token", (string)null);
                });

            modelBuilder.Entity("Sallvat.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_log_entity_created");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Sallvat.Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("GuestTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("guest_token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_cart");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_cart_coupon_id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_customer_id")
                        .HasFilter("customer_id IS NOT NULL");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_cart_expires_at_utc");

                    b.HasIndex("GuestTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_guest_token_hash")
                        .HasFilter("guest_token_hash IS NOT NULL");

                    b.ToTable("cart", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_owner", "(guest_token_hash IS NOT NULL AND customer_id IS NULL) OR (guest_token_hash IS NULL AND customer_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Carts.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReferenceUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("reference_unit_price");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_cart_item");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_item_cart_variant");

                    b.ToTable("cart_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_item_currency", "currency = 'BRL'");

                            t.HasCheckConstraint("ck_cart_item_quantity", "quantity BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_cart_item_reference_price", "reference_unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_notes");

                    b.Property<string>("Concentration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concentration");

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HeartNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("heart_notes");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Longevity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("longevity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Occasions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("occasions");

                    b.Property<string>("OlfactoryFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("olfactory_family");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("period");

                    b.Property<string>("Projection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("projection");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("season");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TopNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("top_notes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_product_slug");

                    b.HasIndex("Status", "IsFeatured", "PublishedAtUtc")
                        .HasDatabaseName("ix_product_publication");

                    b.ToTable("product", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_status", "status IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_product_image");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_image_cover")
                        .HasFilter("is_cover");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_product_image_storage_key");

                    b.HasIndex("ProductId", "Position")
                        .HasDatabaseName("ix_product_image_product_position");

                    b.ToTable("product_image", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_image_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_product_image_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductSlugHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_product_slug_history");

                    b.HasIndex("ProductId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_product_slug_history_slug");

                    b.ToTable("product_slug_history", (string)null);
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LengthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("length_cm");

                    b.Property<string>("NormalizedSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_sku");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("volume_ml");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("weight_kg");

                    b.Property<decimal>("WidthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("width_cm");

                    b.HasKey("Id")
                        .HasName("pk_product_variant");

                    b.HasIndex("NormalizedSku")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variant_normalized_sku");

                    b.HasIndex("ProductId", "IsActive")
                        .HasDatabaseName("ix_product_variant_product_active");

                    b.ToTable("product_variant", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variant_currency", "currency = 'BRL'");

                            t.HasCheckConstraint("ck_product_variant_physical", "weight_kg > 0 AND height_cm > 0 AND width_cm > 0 AND length_cm > 0");

                            t.HasCheckConstraint("ck_product_variant_price", "price >= 0");

                            t.HasCheckConstraint("ck_product_variant_stock", "on_hand >= 0 AND reserved >= 0 AND reserved <= on_hand");

                            t.HasCheckConstraint("ck_product_variant_volume", "volume_ml > 0");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Customers.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complement");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("postal_code")
                        .IsFixedLength();

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("state_code")
                        .IsFixedLength();

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("CustomerId", "IsActive")
                        .HasDatabaseName("ix_address_customer_active");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("Sallvat.Domain.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_application_user_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_customer_normalized_email");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Sallvat.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("ResultingOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_on_hand");

                    b.Property<int>("ResultingReserved")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_reserved");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movement");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ProductVariantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_inventory_movement_variant_created");

                    b.ToTable("inventory_movement", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movement_balance", "resulting_on_hand >= 0 AND resulting_reserved >= 0 AND resulting_reserved <= resulting_on_hand");

                            t.HasCheckConstraint("ck_inventory_movement_quantity", "quantity <> 0");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Inventory.StockReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("released_at_utc");

                    b.Property<DateTimeOffset>("ReservedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reserved_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_reservation");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_stock_reservation_variant_id");

                    b.HasIndex("OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_reservation_order_variant");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_stock_reservation_status_expiration");

                    b.ToTable("stock_reservation", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservation_completion", "(status = 'Reserved' AND consumed_at_utc IS NULL AND released_at_utc IS NULL) OR (status = 'Consumed' AND consumed_at_utc IS NOT NULL AND released_at_utc IS NULL) OR (status = 'Released' AND consumed_at_utc IS NULL AND released_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_stock_reservation_expiration", "expires_at_utc > reserved_at_utc");

                            t.HasCheckConstraint("ck_stock_reservation_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_stock_reservation_status", "status IN ('Reserved', 'Consumed', 'Released')");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AttentionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attention_reason");

                    b.Property<DateTimeOffset?>("AttentionSinceUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("attention_since_utc");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("buyer_phone");

                    b.Property<Guid>("CheckoutAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_attempt_id");

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("coupon_code");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_total");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("grand_total");

                    b.Property<decimal>("ItemsSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("items_subtotal");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("ShippingCarrier")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shipping_carrier");

                    b.Property<int>("ShippingMaximumBusinessDays")
                        .HasColumnType("integer")
                        .HasColumnName("shipping_maximum_business_days");

                    b.Property<int>("ShippingMinimumBusinessDays")
                        .HasColumnType("integer")
                        .HasColumnName("shipping_minimum_business_days");

                    b.Property<string>("ShippingProvider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("shipping_provider");

                    b.Property<string>("ShippingQuoteId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("shipping_quote_id");

                    b.Property<DateTimeOffset>("ShippingQuotedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipping_quoted_at_utc");

                    b.Property<string>("ShippingService")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("shipping_service");

                    b.Property<decimal>("ShippingTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_total");

                    b.Property<Guid>("SourceCartId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_cart_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CheckoutAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_order_checkout_attempt");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_order_coupon_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_order_number");

                    b.HasIndex("SourceCartId")
                        .HasDatabaseName("ix_order_source_cart");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_order_status_created");

                    b.ToTable("order", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_amounts", "items_subtotal >= 0 AND discount_total >= 0 AND discount_total <= items_subtotal AND shipping_total > 0 AND grand_total = items_subtotal - discount_total + shipping_total");

                            t.HasCheckConstraint("ck_order_attention", "(status = 'RequiresAttention' AND attention_reason IS NOT NULL AND attention_since_utc IS NOT NULL) OR (status <> 'RequiresAttention' AND attention_reason IS NULL AND attention_since_utc IS NULL)");

                            t.HasCheckConstraint("ck_order_coupon", "(discount_total = 0 AND coupon_id IS NULL AND coupon_code IS NULL) OR (discount_total > 0 AND coupon_id IS NOT NULL AND coupon_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_order_currency", "currency = 'BRL'");

                            t.HasCheckConstraint("ck_order_expiration", "expires_at_utc > created_at_utc AND shipping_quoted_at_utc <= created_at_utc");

                            t.HasCheckConstraint("ck_order_shipping_days", "shipping_minimum_business_days > 0 AND shipping_maximum_business_days >= shipping_minimum_business_days");

                            t.HasCheckConstraint("ck_order_status", "status IN ('PendingPayment', 'Paid', 'Preparing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded', 'RequiresAttention')");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.OrderAddress", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complement");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("district");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("postal_code")
                        .IsFixedLength();

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("state_code")
                        .IsFixedLength();

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("street");

                    b.HasKey("OrderId")
                        .HasName("pk_order_address");

                    b.ToTable("order_address", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_address_country", "country_code = 'BR'");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("product_name");

                    b.Property<long>("ProductVariantId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_item_order_id");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_order_item_variant_id");

                    b.ToTable("order_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_item_amounts", "unit_price >= 0 AND discount_amount >= 0 AND discount_amount <= unit_price * quantity AND subtotal = unit_price * quantity - discount_amount");

                            t.HasCheckConstraint("ck_order_item_currency", "currency = 'BRL'");

                            t.HasCheckConstraint("ck_order_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Promotions.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClaimedUsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("claimed_usage_count");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinimumSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_subtotal");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_code");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at_utc");

                    b.Property<int?>("TotalUsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("total_usage_limit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("UsageLimitPerIdentity")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit_per_identity");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_coupon");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("ux_coupon_normalized_code");

                    b.HasIndex("IsActive", "StartsAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("ix_coupon_active_window");

                    b.ToTable("coupon", null, t =>
                        {
                            t.HasCheckConstraint("ck_coupon_claimed_usage_count", "claimed_usage_count >= 0 AND (total_usage_limit IS NULL OR claimed_usage_count <= total_usage_limit)");

                            t.HasCheckConstraint("ck_coupon_discount_type", "discount_type IN ('Percentage', 'FixedAmount')");

                            t.HasCheckConstraint("ck_coupon_minimum_subtotal", "minimum_subtotal >= 0");

                            t.HasCheckConstraint("ck_coupon_percentage", "discount_type <> 'Percentage' OR value <= 100");

                            t.HasCheckConstraint("ck_coupon_total_usage_limit", "total_usage_limit IS NULL OR total_usage_limit > 0");

                            t.HasCheckConstraint("ck_coupon_usage_limit_per_identity", "usage_limit_per_identity IS NULL OR usage_limit_per_identity > 0");

                            t.HasCheckConstraint("ck_coupon_value", "value > 0");

                            t.HasCheckConstraint("ck_coupon_window", "starts_at_utc IS NULL OR expires_at_utc IS NULL OR expires_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("Sallvat.Domain.Promotions.CouponRedemption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at_utc");

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("ReservationKey")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_key");

                    b.Property<DateTimeOffset>("ReservedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reserved_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_coupon_redemption");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_coupon_redemption_customer_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_coupon_redemption_order_id");

                    b.HasIndex("ReservationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_coupon_redemption_reservation_key");

                    b.HasIndex("CouponId", "CustomerId", "Status")
                        .HasDatabaseName("ix_coupon_redemption_customer_usage");

                    b.HasIndex("CouponId", "NormalizedEmail", "Status")
                        .HasDatabaseName("ix_coupon_redemption_email_usage");

                    b.HasIndex("CouponId", "Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_coupon_redemption_coupon_status_expiration");

                    b.ToTable("coupon_redemption", null, t =>
                        {
                            t.HasCheckConstraint("ck_coupon_redemption_discount", "discount_amount > 0");

                            t.HasCheckConstraint("ck_coupon_redemption_expiration", "expires_at_utc > reserved_at_utc");

                            t.HasCheckConstraint("ck_coupon_redemption_identity", "customer_id IS NOT NULL OR normalized_email IS NOT NULL");

                            t.HasCheckConstraint("ck_coupon_redemption_order", "(status = 'Reserved' AND order_id IS NULL AND consumed_at_utc IS NULL AND released_at_utc IS NULL) OR (status = 'Consumed' AND order_id IS NOT NULL AND consumed_at_utc IS NOT NULL AND released_at_utc IS NULL) OR (status = 'Released' AND released_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_coupon_redemption_status", "status IN ('Reserved', 'Consumed', 'Released')");
                        });
                });

            modelBuilder.Entity("Sallvat.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_application_user");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_application_user_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_application_user_normalized_user_name");

                    b.ToTable("application_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_role_claim_role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_user_claim_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_user_login_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_user_role_role");

                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_user_role_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_user_token_user");
                });

            modelBuilder.Entity("Sallvat.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_actor");
                });

            modelBuilder.Entity("Sallvat.Domain.Carts.Cart", b =>
                {
                    b.HasOne("Sallvat.Domain.Promotions.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cart_coupon");

                    b.HasOne("Sallvat.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cart_customer");
                });

            modelBuilder.Entity("Sallvat.Domain.Carts.CartItem", b =>
                {
                    b.HasOne("Sallvat.Domain.Carts.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_cart");

                    b.HasOne("Sallvat.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_variant");
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("Sallvat.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_image_product");
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductSlugHistory", b =>
                {
                    b.HasOne("Sallvat.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_slug_history_product");
                });

            modelBuilder.Entity("Sallvat.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Sallvat.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_product");
                });

            modelBuilder.Entity("Sallvat.Domain.Customers.Address", b =>
                {
                    b.HasOne("Sallvat.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_address_customer");
                });

            modelBuilder.Entity("Sallvat.Domain.Customers.Customer", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Sallvat.Domain.Customers.Customer", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_application_user");
                });

            modelBuilder.Entity("Sallvat.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Sallvat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_movement_actor");

                    b.HasOne("Sallvat.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movement_variant");
                });

            modelBuilder.Entity("Sallvat.Domain.Inventory.StockReservation", b =>
                {
                    b.HasOne("Sallvat.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservation_order");

                    b.HasOne("Sallvat.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservation_variant");
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.Order", b =>
                {
                    b.HasOne("Sallvat.Domain.Promotions.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_coupon");

                    b.HasOne("Sallvat.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.OrderAddress", b =>
                {
                    b.HasOne("Sallvat.Domain.Orders.Order", null)
                        .WithOne()
                        .HasForeignKey("Sallvat.Domain.Orders.OrderAddress", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_address_order");
                });

            modelBuilder.Entity("Sallvat.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Sallvat.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order");

                    b.HasOne("Sallvat.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_variant");
                });

            modelBuilder.Entity("Sallvat.Domain.Promotions.CouponRedemption", b =>
                {
                    b.HasOne("Sallvat.Domain.Promotions.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemption_coupon");

                    b.HasOne("Sallvat.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coupon_redemption_customer");

                    b.HasOne("Sallvat.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coupon_redemption_order");
                });
#pragma warning restore 612, 618
        }
    }
}
